CREATE TABLE BOARD(
   SEQ NUMBER PRIMARY KEY,
   WRITER VARCHAR2(20),
   TITLE VARCHAR2(50),
   CONTENT VARCHAR2(2000),
   REGDATE DATE,
   CNT NUMBER
);

CREATE SEQUENCE BOARDSEQ;

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL, '임섭순', '심심', '주글래', SYSDATE, 0);

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL, '지성', '상상', '이루다', SYSDATE, 0);

Delete board
where seq=2;
select * from board;

CREATE TABLE USERTAB(
	ID			VARCHAR2(20) PRIMARY KEY,
	PWD			VARCHAR2(20) ,
	NAME		VARCHAR2(20) ,
	EMAIL		VARCHAR2(50) ,
	GENDER		VARCHAR2(10) ,
	PHONENUMBER	VARCHAR2(20)
);
INSERT INTO USERTAB
VALUES('jslim','jslim', '상상', '이루다', '이루다', 'xxx-xxxx-xxxx');
select * from USERTAB;


