select * from ACORNMEM;

CREATE TABLE CUSTOMERBBS(
	SEQ NUMBER PRIMARY KEY,
	TITLE VARCHAR2(50)
);

CREATE SEQUENCE CUSTOMERBBSSEQ;

INSERT INTO CUSTOMERBBS
VALUES(CUSTOMERBBSSEQ.NEXTVAL, '무엇인가 할때에는');

INSERT INTO CUSTOMERBBS
VALUES(CUSTOMERBBSSEQ.NEXTVAL, '많은 생각을');

INSERT INTO CUSTOMERBBS
VALUES(CUSTOMERBBSSEQ.NEXTVAL, '갖고 행동해야');

INSERT INTO CUSTOMERBBS
VALUES(CUSTOMERBBSSEQ.NEXTVAL, '될때가 있다.');

SELECT * FROM CUSTOMERBBS;

SELECT * FROM BOARD;

Delete board;

ALTER SEQUENCE boardseq INCREMENT BY 1;

insert into board values(boardseq.nextval,'sfd','fs','sf',sysdate,0);

 CREATE TABLE REPLY(
 	RSEQ 		NUMBER PRIMARY KEY,
 	RCONTENT 	VARCHAR2(100),
 	RWRITER 	VARCHAR2(20),
 	SEQ 		NUMBER 	REFERENCES BOARD(SEQ)
 );
 
 CREATE SEQUENCE REPLYSEQ;
 
 insert into REPLY values(REPLYSEQ.nextval,'sfd','홍길동',55);
 
 insert into REPLY values(REPLYSEQ.nextval,'맞네요 되네요','홍길동',55);
 
 
 select * from REPLY;











