--연습문제 6
CREATE OR REPLACE PROCEDURE BIRTH_INFO2
(BIRTH_DATA IN VARCHAR2)
IS 
BIRTH_NO VARCHAR(20);
BEGIN
BIRTH_NO := BIRTH_DATA;
 DBMS_OUTPUT.PUT_LINE( '생년월일 : ' || SUBSTR(BIRTH_NO,1,4) ||'년 '|| SUBSTR(BIRTH_NO,5,2) || '월 ' || SUBSTR(BIRTH_NO,7,2) || '일');
END;
/